@startuml
skinparam classAttributeIconSize 0

' ================ UTILIZADORES ================
class Utilizador {
  +id: String-GUID
  +hashPassword: String
  +role: Perfil
  +dataCriacao: DateTime
  +dataAtualizacao: DateTime
}

class UtilizadorFinal {
  +nome: String
  +dataNasc: Date
  +morada: String
  +codPostal: String
  +email: String
  +contactoTelefone: String
  +numOwnerships: int
  +numApadrinhamentos: int
}

class AdminCAA {
}

Utilizador <|-- UtilizadorFinal
Utilizador <|-- AdminCAA

' ================ CAA (Centro de Acolhimento Animal) ================
class CAA {
  +id: String-GUID
  +nome: String
  +morada: String
  +distrito: String
  +email: String
  +contacto: String
  +imageUrlPath: String
  +descricaoImagem: String
  +dataCriacao: DateTime
}


' ================ ANIMAIS ================
class Animal {
  +id: String-GUID
  +nome: String
  +especie: String
  +raca: String
  +cor: String
  +sexo: Sexo
  +porte: Porte
  +dataNasc: Date
  +esterilizado: Boolean
  +caracteristicas: String
  +dataEntrada: Date
  +estadoAdocao: EstadoAdocao
  +descricao: String
  +dataCriacao: DateTime
  +dataAtualizacao: DateTime
}

class ImagemAnimal {
  +id: String-GUID
  +imageUrlPath: String
  +legenda: String
  +imagemPrincipal: Boolean
  +createdAt: DateTime
}

' ================ APADRINHAMENTO (Fostering) ================
class Apadrinhamento {
  +id: String-GUID
  +valorMensal: Decimal
  +dataInicio: Date
  +dataFim: Date
  +estado: EstadoApadrinhamento
  +dataCriacao: DateTime
  +dataAtualizacao: DateTime
}

' ================ Convivencia (SlotConvivencia + PeriodoConvivencia) ================
class Convivencia {
  +id: String-GUID
  +dataHoraInicio: DateTime
  +dataHoraFim: DateTime
  +estado: estadoConvivencia
  +dataCriacao: DateTime
}

' ================ VÍNCULO RESPONSÁVEL (Ownership) ================
class Ownership {
  +id: String-GUID
  +dataInicio: Date
  +dataFim: Date
  +estado: EstadoVinculo
  +custoMensalEstimadoOwnership: Decimal
  +estadoPedido: EstadoPedido
  +dataSubmissao: DateTime
  +dataAprovacao: DateTime
  +motivoRecusa: String
}

' ================ PAGAMENTOS (Mock) ================
class Pagamento {
  +id: String-GUID
  +valor: Decimal
  +dataPagamento: Date
  +dataVencimento: Date
  +estado: Boolean
  +descricao: String
  +createdAt: DateTime
}

' ================ OUTROS ================
class Favorito {
  +id: String-GUID
  +createdAt: DateTime
  +estadoAtivo: Boolean
}

class Notificacao {
  +id: String-GUID
  +titulo: String
  +mensagem: String
  +tipo: TipoNotificacao
  +lida: Boolean
  +createdAt: DateTime
}

' ================ ENUMS ================
enum Perfil {
  UTILIZADOR_FINAL
  ADMIN_CAA
}

enum Sexo {
  M
  F
}

enum EstadoConvivencia {
  ATIVO
  CANCELADO
  EFETUADO
}

enum Porte {
  PEQUENO
  MEDIO
  GRANDE
}

enum EstadoAdocao {
  DISPONIVEL
  APADRINHADO
  APADRINHADO_TOTALMENTE
  OWNERSHIP
  INATIVO
}

enum EstadoApadrinhamento {
  ATIVO
  CANCELADO
  CONCLUIDO
}

enum EstadoVinculo {
  ATIVO
  TERMINADO
}

enum EstadoPedido {
  PENDENTE
  EM_ANALISE
  APROVADO
  RECUSADO
}

enum TipoNotificacao {
  PEDIDO_OWNERSHIP_APROVADO
  PEDIDO_OWNERSHIP_RECUSADO
  PAGAMENTO_CONFIRMADO
  SLOT_CONFIRMADO
  GERAL
}

' ================ RELAÇÕES CAA ================
AdminCAA "1" -- "1" CAA : gere
CAA "1" -- "0..*" Animal : abriga

' ================ RELAÇÕES ANIMAL ================
Animal "1" *-- "1..*" ImagemAnimal : possui
Convivencia "0..*" -- "1" Animal

' ================ RELAÇÕES APADRINHAMENTO ================
UtilizadorFinal "1" -- "0..*" Apadrinhamento : patrocina
Apadrinhamento  "0..*" -- "1" Animal : beneficia
Apadrinhamento  "1" -- "0..*" Convivencia : agenda
Apadrinhamento  "1" -- "0..*" Pagamento : gera

' ================ RELAÇÕES VÍNCULO RESPONSÁVEL ================
UtilizadorFinal "1" -- "0..*" Ownership : solicita
Ownership "0..1" -- "1" Animal : vincula
Ownership "1" -- "0..*" Convivencia : agenda
Ownership "1" -- "0..*" Pagamento : associado

' ================ RELAÇÕES UTILIZADOR ================
UtilizadorFinal "1" -- "0..*" Favorito : marca
Favorito "0..*" -- "1" Animal : refere

UtilizadorFinal "1" -- "0..*" Notificacao : recebe
@enduml
